SET foreign_key_checks = 0;
truncate table logininfo;
ALTER TABLE logininfo AUTO_INCREMENT = 1;
truncate table practiceanswer;
ALTER TABLE practiceanswer AUTO_INCREMENT = 1;
truncate table practice;
ALTER TABLE practice AUTO_INCREMENT = 1;
truncate table examanswer;
ALTER TABLE examanswer AUTO_INCREMENT = 1;
truncate table examdetail;
ALTER TABLE examdetail AUTO_INCREMENT = 1;
truncate table exam;
ALTER TABLE exam AUTO_INCREMENT = 1;
truncate table classrooms;
ALTER TABLE classrooms AUTO_INCREMENT = 1;
truncate table courses;
ALTER TABLE courses AUTO_INCREMENT = 1;
truncate table student;
ALTER TABLE student AUTO_INCREMENT = 1;
truncate table teacher;
ALTER TABLE teacher AUTO_INCREMENT = 1;
truncate table users;
ALTER TABLE users AUTO_INCREMENT = 1;
SET foreign_key_checks = 1;